//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pornWs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        public System.Guid id { get; set; }
        public string ChannekId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Img { get; set; }
        public string PublishDate { get; set; }
        public string Url { get; set; }
        public string Views { get; set; }
        public string Search { get; set; }
        public string Comment { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> Creation { get; set; }
        public string Rank { get; set; }
        public Nullable<bool> State { get; set; }
    }
}
