//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xxx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        public System.Guid id { get; set; }
        public string ChannekId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Img { get; set; }
        public string PublishDate { get; set; }
        public string Url { get; set; }
        public string Views { get; set; }
        public string Search { get; set; }
        public string Comment { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> Creation { get; set; }
        public string Rank { get; set; }
        public Nullable<bool> State { get; set; }
    }
}
